import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import AuthProvider from "./auth/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html data-theme='corporate' lang='en'>
			<body className={inter.className}>
				<AuthProvider>
					<Navbar />
					<main className='p-5'>{children}</main>
				</AuthProvider>
			</body>
		</html>
	);
}
